### ISSUE TITLE
Support python setup.py test

### ISSUE THREAD

**Issue by earlchew** [sassoftware/python-keyutils#18] opened 2017-08-02 15:11 UTC
* http://python-packaging.readthedocs.io/en/latest/testing.html

```
======================================================================
ERROR: testTimeout (test.keyutils_test.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earl/Development/python-keyutils/test/keyutils_test.py", line 91, in testTimeout
    self.assertEqual(keyutils.request_key(desc, keyring), None)
  File "/home/earl/Development/python-keyutils/keyutils/__init__.py", line 36, in request_key
    return _keyutils.request_key(keyType, key, None, keyring)
  File "keyutils/_keyutils.pyx", line 94, in keyutils._keyutils.request_key (keyutils/_keyutils.c:1274)
    with nogil:
error: (127, 'Key has expired')

----------------------------------------------------------------------
Ran 6 tests in 1.502s
```

**Comment by mibanescu** [comment] 2017-08-02 15:24
Thanks, will add support for python 3.6 at the same time.

**Comment by mibanescu** [comment] 2017-08-03 19:28
Interestingly, on my fedora 26 system the key is never marked as being expired. Once it expires, the underlying C call turns into an ENOKEY, which is the reason why the test did pass on my system.
Which os/distro/kernel/keyutils package combination do you have, that issues the "Key has expired" call?

**Comment by earlchew** [comment] 2017-08-03 20:44
Maybe this has something to do with the garbage collection period?

https://www.kernel.org/doc/Documentation/security/keys.txt

```
Dead keys (for which the type has been removed) will be automatically unlinked
from those keyrings that point to them and deleted as soon as possible by a
background garbage collector.

Similarly, revoked and expired keys will be garbage collected, but only after a
certain amount of time has passed.  This time is set as a number of seconds in:

	/proc/sys/kernel/keys/gc_delay
```

I saw the error on Ubuntu 14.04.5 LTS

**Comment by mibanescu** [comment] 2017-08-04 16:02
I have 300 seconds in /proc/sys/kernel/keys/gc_delay, so that doesn't explain it either.

**Comment by earlchew** [comment] 2017-08-04 16:17
I tested on:
```
Linux xxxxxx 3.13.0-102-generic #149-Ubuntu SMP Wed Nov 9 21:52:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mibanescu** [comment] 2017-08-04 19:44
Linux xxxxxx 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mibanescu** [comment] 2017-08-04 19:55
Linux xxxxxx 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Confirmed the exception does get raised on this 3.x kernel.

**Comment by earlchew** [comment] 2017-08-06 15:37
This change in behaviour might be related to https://patchwork.kernel.org/patch/5336891/

**Closed** 2017-08-07 18:45 UTC
